### PUT request to update user by id
PUT http://localhost:8080/api/v1/users/40915860-dc24-438e-98c2-d1751e4c3ff0
Content-Type: application/json

{
  "password":"123123123",
  "firstName": "Kaka",
  "lastName":"Dev",
  "avatarUrl": "https://example.com/avatar123.jpg"
}

###